
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author User
 */
public class Menu_Page extends javax.swing.JFrame {
    // ใช้กับการดึงตาราง
    private Connection con = null;
    private ResultSet rs = null; //ดึงข้อมูลทั้งหมดมาเป็นก้อน
    private Statement st = null;

    /**
     * Creates new form EDIT_MENU
     */
    public Menu_Page() {
        initComponents();
        con= MyConnection.getConnection();
        Show_Menu_IN_JTable();
    }
    
    public ArrayList<Menu> getMenuList(){
        ArrayList<Menu> menuList = new ArrayList<Menu>();
        con = MyConnection.getConnection(); //เชื่อม database
        String query = "select * from menu"; //เชื่อมตาราง menu
        
        try{
            st = con.createStatement();
            rs = st.executeQuery(query);
            Menu menu;
            while(rs.next()){
                menu = new Menu(rs.getString("username_menu"), rs.getString("category_menu"), rs.getString("name"), rs.getInt("price"));
                System.out.println("run menu");
//                user = new User(rs.getInt("ID"),rs.getString("Name"),rs.getString("Surname"),rs.getInt("Age"));
                menuList.add(menu);
            }
        } catch (Exception e){
            e.printStackTrace();
        }
        return menuList;
    }
    
    //Display Data in Table
    
    public void Show_Menu_IN_JTable(){
        
        ArrayList<Menu> list = getMenuList();
        DefaultTableModel model = (DefaultTableModel)jTable_Menu.getModel();
        Object[] row = new Object[2];
        for(int i=0; i<list.size();i++){
            row[0] = list.get(i).getName();
            row[1] = list.get(i).getPrice();
            
            model.addRow(row);
        }
    }
    
    // Execute SQL Query
    public void executeSQLQuery(String query, String Message){
        con = MyConnection.getConnection(); //เชื่อม database
        try{
            st = con.createStatement();
            if(st.executeUpdate(query) != 0){
                //refresh JTable
                DefaultTableModel model = (DefaultTableModel)jTable_Menu.getModel();
                model.setRowCount(0);
                Show_Menu_IN_JTable();
                
                JOptionPane.showMessageDialog(null, "Data "+Message+" Success");
            }else{
                JOptionPane.showMessageDialog(null, "Data not "+Message);
            }
        } catch (HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(null, "Data not "+e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Back = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Menu = new javax.swing.JTable();
        jLabel_Category = new javax.swing.JLabel();
        jButton_EditCategory = new javax.swing.JButton();
        jButton_DeleteCategory = new javax.swing.JButton();
        jTextField_PriceMenu = new javax.swing.JTextField();
        jTextField_NameMenu = new javax.swing.JTextField();
        jButton_AddMenu = new javax.swing.JButton();
        jButton_UpdateMenu = new javax.swing.JButton();
        jButton_DeleteMenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(28, 64, 121));

        jLabel2.setFont(new java.awt.Font("TH SarabunPSK", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("  😃 HOM-KLIN-NGERN");

        Back.setFont(new java.awt.Font("TH SarabunPSK", 1, 18)); // NOI18N
        Back.setText("BACK");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Back, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Back))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTable_Menu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Menu", "Price"
            }
        ));
        jScrollPane1.setViewportView(jTable_Menu);

        jLabel_Category.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel_Category.setText("Category");

        jButton_EditCategory.setText("Edit");
        jButton_EditCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_EditCategoryActionPerformed(evt);
            }
        });

        jButton_DeleteCategory.setText("Delete");
        jButton_DeleteCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_DeleteCategoryActionPerformed(evt);
            }
        });

        jTextField_PriceMenu.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jTextField_PriceMenu.setText("Enter Price");
        jTextField_PriceMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_PriceMenuActionPerformed(evt);
            }
        });

        jTextField_NameMenu.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jTextField_NameMenu.setText("Enter Name");
        jTextField_NameMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_NameMenuActionPerformed(evt);
            }
        });

        jButton_AddMenu.setText("Add");
        jButton_AddMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AddMenuActionPerformed(evt);
            }
        });

        jButton_UpdateMenu.setText("Update");
        jButton_UpdateMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_UpdateMenuActionPerformed(evt);
            }
        });

        jButton_DeleteMenu.setText("Delete");
        jButton_DeleteMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_DeleteMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField_NameMenu)
                    .addComponent(jTextField_PriceMenu)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton_AddMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                        .addComponent(jButton_UpdateMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(jButton_DeleteMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel_Category, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_EditCategory)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_DeleteCategory)
                        .addGap(4, 4, 4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(12, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_Category)
                            .addComponent(jButton_EditCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_DeleteCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField_NameMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField_PriceMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_AddMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_UpdateMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_DeleteMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(94, 94, 94))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        HOME_JFrame Hf = new HOME_JFrame();
        Hf.setVisible(true);
        Hf.pack();
        Hf.setLocationRelativeTo(null);
        Hf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_BackActionPerformed

    private void jButton_EditCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_EditCategoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_EditCategoryActionPerformed

    private void jButton_DeleteCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_DeleteCategoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_DeleteCategoryActionPerformed

    private void jTextField_PriceMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_PriceMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_PriceMenuActionPerformed

    private void jTextField_NameMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_NameMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_NameMenuActionPerformed

    private void jButton_AddMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AddMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_AddMenuActionPerformed

    private void jButton_UpdateMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_UpdateMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_UpdateMenuActionPerformed

    private void jButton_DeleteMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_DeleteMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_DeleteMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EDIT_MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EDIT_MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EDIT_MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EDIT_MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EDIT_MENU().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton jButton_AddMenu;
    private javax.swing.JButton jButton_DeleteCategory;
    private javax.swing.JButton jButton_DeleteMenu;
    private javax.swing.JButton jButton_EditCategory;
    private javax.swing.JButton jButton_UpdateMenu;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel_Category;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_Menu;
    private javax.swing.JTextField jTextField_NameMenu;
    private javax.swing.JTextField jTextField_PriceMenu;
    // End of variables declaration//GEN-END:variables
}
